
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class T_Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public T_Product()
    {

        this.T_Sale = new HashSet<T_Sale>();

        this.T_Supply = new HashSet<T_Supply>();

    }


    public int id_product { get; set; }

    public string Title { get; set; }

    public int id_manufacturer { get; set; }

    public int id_type_pro { get; set; }

    public int id_supply { get; set; }



    public virtual T_Manufacturer T_Manufacturer { get; set; }

    public virtual T_Type_pro T_Type_pro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_Sale> T_Sale { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_Supply> T_Supply { get; set; }

}

}
